package com.tripbook.app.ui.booking

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment

/**
 * STUB — To be fully implemented by backend partner.
 *
 * This screen shows:
 *   - Booking reference number (generated by Firestore)
 *   - Site name + date + traveller count summary
 *   - Company contact info
 *   - "Go Home" button → navigates back to HomeFragment
 */
class BookingConfirmationFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return TextView(requireContext()).apply {
            text = "Booking Confirmation\n(Backend partner implements this)"
            setPadding(48, 48, 48, 48)
            textSize = 16f
        }
    }
}